# Generated by Django 5.0.3 on 2024-05-14 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinfo",
            name="activities",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="albums",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="audios",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="bdate",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="books",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="city",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="country",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="crop_photo",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="education_form",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="education_status",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="faculty",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="first_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="followers_count",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="friends",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="games",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="gifts",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="graduation",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="groups",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="home_town",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="inspired_by",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="interests",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="is_account_closed",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="langs",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="last_name",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="length_posts",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="movies",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="music",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="photos",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="quotes",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="religion",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="schools",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="status_text",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="subscriptions_on_profiles",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="university",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="user_id",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="username",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="verified",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="userinfo",
            name="videos",
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="link",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.link"
            ),
        ),
    ]
