# Generated by Django 5.0.3 on 2024-05-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_userinfo_activities_userinfo_albums_userinfo_audios_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userinfo",
            options={},
        ),
        migrations.AddField(
            model_name="userinfo",
            name="frends_data",
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
